name: 📚 Deploy Documentation

on:
  push:
    branches: [ main ]
    paths: 
      - 'docs/**'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ main ]
    paths: 
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'docs/package-lock.json'

    - name: 📦 Install dependencies
      run: |
        cd docs
        if [ -f package-lock.json ]; then
          npm ci --prefer-offline --no-audit
        else
          npm install --prefer-offline --no-audit
        fi

    - name: 🔧 Setup Pages
      uses: actions/configure-pages@v4

    - name: 🔍 Validate documentation
      run: |
        cd docs
        echo "📋 检查文档结构..."
        [ -f index.html ] || { echo "❌ 缺少 index.html"; exit 1; }
        [ -f README.md ] || { echo "❌ 缺少 README.md"; exit 1; }
        echo "✅ 文档结构验证完成"

    - name: 🔍 Lint Markdown (strict)
      run: |
        cd docs
        echo "📝 Markdown linting..."
        npm run lint

    - name: 🔗 Check links (strict)
      run: |
        cd docs
        echo "🔍 检查文档链接..."
        npm run check-links

    - name: 🛠️ Build documentation
      run: |
        cd docs
        echo "🏗️ docsify 静态站点，无需额外构建"
        echo "📄 生成 sitemap.xml ..."
        cat > sitemap.xml << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
          <url>
            <loc>https://telegram-sdk.xbot.my/</loc>
            <changefreq>daily</changefreq>
            <priority>1.0</priority>
          </url>
          <url>
            <loc>https://telegram-sdk.xbot.my/#/guide/installation</loc>
            <changefreq>weekly</changefreq>
            <priority>0.8</priority>
          </url>
          <url>
            <loc>https://telegram-sdk.xbot.my/#/guide/quick-start</loc>
            <changefreq>weekly</changefreq>
            <priority>0.8</priority>
          </url>
          <url>
            <loc>https://telegram-sdk.xbot.my/#/guide/configuration</loc>
            <changefreq>weekly</changefreq>
            <priority>0.8</priority>
          </url>
          <url>
            <loc>https://telegram-sdk.xbot.my/#/api/</loc>
            <changefreq>weekly</changefreq>
            <priority>0.7</priority>
          </url>
        </urlset>
        EOF
        echo "🤖 生成 robots.txt..."
        echo "User-agent: *\nAllow: /" > robots.txt
        echo "✅ 文档构建完成"

    - name: 📊 Generate build info
      run: |
        cd docs
        cat > build-info.json << EOF
{
  "buildTime": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
  "commit": "${{ github.sha }}",
  "branch": "${{ github.ref_name }}",
  "workflow": "${{ github.workflow }}",
  "actor": "${{ github.actor }}"
}
EOF

    - name: 📤 Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs

    - name: 📝 Comment on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `📚 文档构建完成 ✅\n\n提交: \`${{ github.sha }}\`\n分支: \`${{ github.ref_name }}\`\n触发者: @${{ github.actor }}`
          })

  deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: 🚀 Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

  lighthouse:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: 🚦 Lighthouse CI
      uses: treosh/lighthouse-ci-action@v10
      continue-on-error: true
      with:
        urls: |
          https://telegram-sdk.xbot.my
          https://telegram-sdk.xbot.my/#/guide/quick-start
          https://telegram-sdk.xbot.my/#/api/
        uploadArtifacts: true
        temporaryPublicStorage: true

    - name: 📊 Report Lighthouse summary
      run: |
        echo "📊 Lighthouse 结果已上传到 Artifact"
        echo "👉 请在 Actions 页面下载查看完整报告"